In [8]:
import numpy as np
import pandas as pd
import re

In [50]:
station_co = pd.read_csv("Stations_20180921.csv")
numbat = pd.read_csv("2019_numbat.csv")

In [6]:
station_co.sample(3)

,FID,OBJECTID,NAME,EASTING,NORTHING,LINES,NETWORK,Zone,x,y
472,472,284,Amersham,496372,198181,Metropolitan,London Underground,9,-0.606147,51.673662
104,104,297,West Hampstead,525592,184653,Jubilee,London Underground,2,-0.188569,51.546297
205,205,116,Seven Sisters,533643,188931,Victoria,London Underground,3,-0.070894,51.582895

In [7]:
numbat.sample(3)

,Mode,NLC,ASC,Station,Coverage,year,day,dir,Total,Early,AM_Peak,Inter_Peak,PM_Peak,Evening,Late
2592,LO,1404,ACCr,Acton Central,Station entry / exit,2019,SAT,IN,2199,85,368,1002,432,226,86
660,LU,620,KETu,Kenton,Station entry / exit,2019,FRI,IN,3159,428,1002,855,590,218,66
1908,LU,532,BURu,Burnt Oak,Station entry / exit,2019,SUN,OUT,3292,38,293,1109,876,656,320

In [51]:
pattern = "\s+(?=LU)\w+"

numbat.loc[numbat.Station.str.contains(pattern), :]

,Mode,NLC,ASC,Station,Coverage,year,day,dir,Total,Early,AM_Peak,Inter_Peak,PM_Peak,Evening,Late
10,LU,512,BALu,Balham LU,Station entry / exit,2019,MTT,IN,21144,1375,10422,4221,3381,1317,428
20,LU,520,BNGu,Bethnal Green LU,Station entry / exit,2019,MTT,IN,23350,821,6581,7010,5403,2412,1123
21,LU,521,BLFu,Blackfriars LU,Station entry / exit,2019,MTT,IN,28287,485,6105,6198,11129,3488,882
29,LU,778,BRXu,Brixton LU,Station entry / exit,2019,MTT,IN,52678,3308,23579,10664,7509,3178,4440
36,LU,852,CWFu,Canary Wharf LU,Station entry / exit,2019,MTT,IN,81830,1216,8443,16487,38917,13927,2840
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2103,LU,729,TTHu,Tottenham Hale LU,Station entry / exit,2019,SUN,OUT,12820,245,953,5131,3373,2189,929
2114,LU,777,VUXu,Vauxhall LU,Station entry / exit,2019,SUN,OUT,29156,511,3222,10824,7521,5197,1881
2115,LU,741,VICu,Victoria LU,Station entry / exit,2019,SUN,OUT,81996,1372,9068,33992,21412,12197,3955
2120,LU,747,WLOu,Waterloo LU,Station entry / exit,2019,SUN,OUT,55633,1321,4478,23450,15146,8158,3080
2128,LU,758,WHDu,West Hampstead LU,Station entry / exit,2019,SUN,OUT,8769,127,495,3244,2580,1643,680

In [18]:
pattern = "\s+(?=LU)\w+"

numbat.loc[numbat.U_Station.str.contains(r'\s+(?=DLR)\w+'), :]

,Mode,NLC,ASC,Station,Coverage,year,day,dir,Total,Early,AM_Peak,Inter_Peak,PM_Peak,Evening,Late,U_Station
3047,DLR,842,CAWd,Canary Wharf DLR,Station entry / exit,2019,MTT,IN,31366,527,7357,6855,11461,4033,1133,Canary Wharf DLR
3063,DLR,940,LEWd,Lewisham DLR,Station entry / exit,2019,MTT,IN,16001,1258,8049,3191,2269,876,358,Lewisham DLR
3064,DLR,862,LIMd,Limehouse DLR,Station entry / exit,2019,MTT,IN,13262,814,6593,2844,1850,822,339,Limehouse DLR
3073,DLR,860,SHAd,Shadwell DLR,Station entry / exit,2019,MTT,IN,14017,443,4592,3717,3269,1404,592,Shadwell DLR
3078,DLR,504,STId,Stratford International DLR,Station entry / exit,2019,MTT,IN,6813,385,2359,1500,1676,651,242,Stratford International DLR
3092,DLR,842,CAWd,Canary Wharf DLR,Station entry / exit,2019,MTT,OUT,30948,1088,11244,7173,8320,2403,720,Canary Wharf DLR
3108,DLR,940,LEWd,Lewisham DLR,Station entry / exit,2019,MTT,OUT,15930,307,2164,3150,7216,2306,787,Lewisham DLR
3109,DLR,862,LIMd,Limehouse DLR,Station entry / exit,2019,MTT,OUT,18399,471,2907,3799,7099,2889,1234,Limehouse DLR
3118,DLR,860,SHAd,Shadwell DLR,Station entry / exit,2019,MTT,OUT,14388,331,3616,3172,4258,2108,903,Shadwell DLR
3123,DLR,504,STId,Stratford International DLR,Station entry / exit,2019,MTT,OUT,5650,228,1229,1262,1607,937,387,Stratford International DLR
3137,DLR,842,CAWd,Canary Wharf DLR,Station entry / exit,2019,FRI,IN,27573,463,6468,6025,10076,3545,996,Canary Wharf DLR
3153,DLR,940,LEWd,Lewisham DLR,Station entry / exit,2019,FRI,IN,15881,1209,7195,3483,2377,1080,537,Lewisham DLR
3154,DLR,862,LIMd,Limehouse DLR,Station entry / exit,2019,FRI,IN,13376,697,5814,3115,2102,1044,604,Limehouse DLR
3163,DLR,860,SHAd,Shadwell DLR,Station entry / exit,2019,FRI,IN,14138,411,4030,4020,3253,1560,864,Shadwell DLR
3168,DLR,504,STId,Stratford International DLR,Station entry / exit,2019,FRI,IN,6958,336,2072,1692,1705,827,326,Stratford International DLR
3182,DLR,842,CAWd,Canary Wharf DLR,Station entry / exit,2019,FRI,OUT,28938,1017,10513,6709,7779,2246,674,Canary Wharf DLR
3198,DLR,940,LEWd,Lewisham DLR,Station entry / exit,2019,FRI,OUT,15169,301,2113,3487,6085,2096,1087,Lewisham DLR
3199,DLR,862,LIMd,Limehouse DLR,Station entry / exit,2019,FRI,OUT,18333,435,2946,4163,6144,2911,1734,Limehouse DLR
3208,DLR,860,SHAd,Shadwell DLR,Station entry / exit,2019,FRI,OUT,14761,299,3434,3555,4035,2176,1262,Shadwell DLR
3213,DLR,504,STId,Stratford International DLR,Station entry / exit,2019,FRI,OUT,5789,205,1131,1484,1559,909,501,Stratford International DLR
3227,DLR,842,CAWd,Canary Wharf DLR,Station entry / exit,2019,SAT,IN,12421,119,664,5255,3312,2000,1071,Canary Wharf DLR
3243,DLR,940,LEWd,Lewisham DLR,Station entry / exit,2019,SAT,IN,9955,322,1240,4640,2082,1105,566,Lewisham DLR
3244,DLR,862,LIMd,Limehouse DLR,Station entry / exit,2019,SAT,IN,9089,204,1273,4044,1855,1073,640,Limehouse DLR
3253,DLR,860,SHAd,Shadwell DLR,Station entry / exit,2019,SAT,IN,10183,217,1184,4467,2042,1378,895,Shadwell DLR
3258,DLR,504,STId,Stratford International DLR,Station entry / exit,2019,SAT,IN,5042,96,465,2124,1281,766,310,Stratford International DLR
3272,DLR,842,CAWd,Canary Wharf DLR,Station entry / exit,2019,SAT,OUT,17800,230,1403,8204,4512,2308,1143,Canary Wharf DLR
3288,DLR,940,LEWd,Lewisham DLR,Station entry / exit,2019,SAT,OUT,9899,175,960,4041,2403,1397,923,Lewisham DLR
3289,DLR,862,LIMd,Limehouse DLR,Station entry / exit,2019,SAT,OUT,13115,215,1174,4430,3165,2268,1863,Limehouse DLR
3298,DLR,860,SHAd,Shadwell DLR,Station entry / exit,2019,SAT,OUT,10641,134,946,3900,2581,1829,1251,Shadwell DLR
3303,DLR,504,STId,Stratford International DLR,Station entry / exit,2019,SAT,OUT,4467,84,549,1814,933,645,442,Stratford International DLR
3317,DLR,842,CAWd,Canary Wharf DLR,Station entry / exit,2019,SUN,IN,11706,31,512,5759,3340,1490,574,Canary Wharf DLR
3333,DLR,940,LEWd,Lewisham DLR,Station entry / exit,2019,SUN,IN,7382,93,763,3997,1554,723,252,Lewisham DLR
3334,DLR,862,LIMd,Limehouse DLR,Station entry / exit,2019,SUN,IN,6447,53,851,3201,1273,757,312,Limehouse DLR
3343,DLR,860,SHAd,Shadwell DLR,Station entry / exit,2019,SUN,IN,7416,38,801,3810,1582,857,328,Shadwell DLR
3348,DLR,504,STId,Stratford International DLR,Station entry / exit,2019,SUN,IN,3724,16,311,1684,1057,470,186,Stratford International DLR
3362,DLR,842,CAWd,Canary Wharf DLR,Station entry / exit,2019,SUN,OUT,14531,31,904,8134,3543,1406,513,Canary Wharf DLR
3378,DLR,940,LEWd,Lewisham DLR,Station entry / exit,2019,SUN,OUT,7214,41,559,3217,1885,1056,456,Lewisham DLR
3379,DLR,862,LIMd,Limehouse DLR,Station entry / exit,2019,SUN,OUT,9534,66,779,3541,2617,1780,751,Limehouse DLR
3388,DLR,860,SHAd,Shadwell DLR,Station entry / exit,2019,SUN,OUT,7773,21,550,3115,2135,1383,569,Shadwell DLR
3393,DLR,504,STId,Stratford International DLR,Station entry / exit,2019,SUN,OUT,3428,9,305,1455,786,601,272,Stratford International DLR

In [52]:
numbat['U_Station']=numbat.Station.str.replace(r'\s+(?=LU)\w+', "")

In [53]:
numbat['U_Station1']=numbat.U_Station.str.replace(r'\s+(?=DLR)\w+', "")

In [54]:
numbat.loc[3388]

Mode                           DLR
NLC                            860
ASC                           SHAd
Station               Shadwell DLR
Coverage      Station entry / exit
year                          2019
 day                           SUN
 dir                           OUT
Total                         7773
Early                           21
AM_Peak                        550
Inter_Peak                    3115
PM_Peak                       2135
Evening                       1383
Late                           569
U_Station             Shadwell DLR
U_Station1                Shadwell
Name: 3388, dtype: object

In [55]:
numbat[' day'].unique()

array(['MTT', 'FRI', 'SAT', 'SUN'], dtype=object)

In [45]:
numbat.columns.values

array(['Mode', 'NLC', 'ASC', 'Station', 'Coverage', 'year', ' day',
       ' dir', 'Total', 'Early     ', 'AM_Peak', 'Inter_Peak', 'PM_Peak',
       'Evening   ', 'Late      ', 'U_Station', 'U_Station1'],
      dtype=object)

In [56]:
col_names = ['Mode', 'NLC', 'ASC', 'Station', 'Coverage', 'year', 'day',
       'dir', 'Total', 'Early', 'AM_Peak', 'Inter_Peak', 'PM_Peak',
       'Evening', 'Late', 'U_Station', 'U_Station1']
numbat.columns = col_names

In [37]:
numbat.columns.values

array(['Mode', 'NLC', 'ASC', 'Station', 'Coverage', 'year', 'day', 'dir',
       'Total', 'Early', 'AM_Peak', 'Inter_Peak', 'PM_Peak', 'Evening',
       'Late', 'U_Station', 'U_Station1'], dtype=object)

In [63]:
numbat2 = numbat[['Mode', 'NLC', 'ASC','U_Station1', 'Coverage', 'year', 'day',
       'dir', 'Total', 'Early', 'AM_Peak', 'Inter_Peak', 'PM_Peak',
       'Evening', 'Late']]

In [67]:
numbat2 = numbat2.rename(columns={'U_Station1':'Station'})

In [68]:
numbat2.sample(3)

,Mode,NLC,ASC,Station,Coverage,year,day,dir,Total,Early,AM_Peak,Inter_Peak,PM_Peak,Evening,Late
1938,LU,562,ECTu,Earl's Court,Station entry / exit,2019,SUN,OUT,20306,380,1557,7428,5252,4027,1662
3136,DLR,851,BOCd,Bow Church,Station entry / exit,2019,FRI,IN,6431,186,1653,2004,1489,733,366
1925,LU,548,CPNu,Clapham North,Station entry / exit,2019,SUN,OUT,6036,72,241,1974,1893,1375,481

In [72]:
numbat2.to_csv("2019_numbat_formatted.csv", index=False)

# Data operations here

In [61]:
numbat[ (numbat['day'] == "MTT") & (numbat['dir'] == 'IN') & (numbat['Mode'] == 'LU')].sort_values(by="Total", ascending=False).head(10)

,Mode,NLC,ASC,Station,Coverage,year,day,dir,Total,Early,AM_Peak,Inter_Peak,PM_Peak,Evening,Late,U_Station,U_Station1
244,LU,747,WLOu,Waterloo LU,Station entry / exit,2019,MTT,IN,149888,4141,63134,32773,32755,12284,4801,Waterloo,Waterloo
128,LU,625,KXXu,King's Cross St. Pancras,Station entry / exit,2019,MTT,IN,138167,2451,28824,42605,38648,18935,6704,King's Cross St. Pancras,King's Cross St. Pancras
239,LU,741,VICu,Victoria LU,Station entry / exit,2019,MTT,IN,132807,3458,32730,39593,35913,14166,6947,Victoria,Victoria
139,LU,635,LONu,London Bridge LU,Station entry / exit,2019,MTT,IN,121129,3869,28931,33421,34404,14636,5868,London Bridge,London Bridge
169,LU,669,OXCu,Oxford Circus,Station entry / exit,2019,MTT,IN,114563,432,2960,31326,42556,27884,9405,Oxford Circus,Oxford Circus
11,LU,513,BNKu,Bank and Monument,Station entry / exit,2019,MTT,IN,113772,823,9148,25796,53641,18984,5380,Bank and Monument,Bank and Monument
138,LU,634,LSTu,Liverpool Street LU,Station entry / exit,2019,MTT,IN,111518,2997,24381,29213,36071,13813,5043,Liverpool Street,Liverpool Street
218,LU,719,SFDu,Stratford,Station entry / exit,2019,MTT,IN,97218,6410,21417,28106,25544,12806,2935,Stratford,Stratford
36,LU,852,CWFu,Canary Wharf LU,Station entry / exit,2019,MTT,IN,81830,1216,8443,16487,38917,13927,2840,Canary Wharf,Canary Wharf
170,LU,670,PADu,Paddington TfL,Station entry / exit,2019,MTT,IN,79826,1933,22141,25265,21208,7291,1988,Paddington TfL,Paddington TfL